--- #YAML:1.0
name:                     Acme-CPANAuthors-InMemoriam
version:                  1.05
abstract:                 In honour of our deceased CPAN Authors.
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  perl:                   5.006
  Acme::CPANAuthors:      0.04
recommends:
  Test::CPAN::Meta:       0
  Test::CPAN::Meta::JSON: 0
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
build_requires:
  IO::File:               0
  Test::More:             0.70

provides:
  Acme::CPANAuthors::InMemoriam:
    file:     lib/Acme/CPANAuthors/InMemoriam.pm
    version:  1.05
no_index:
  directory:
    - t
    - examples

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Acme-CPANAuthors-InMemoriam
  repository: http://github.com/barbie/Acme-CPANAuthors-InMemoriam

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
